ALTER TABLE "Message"
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "editedAt" TIMESTAMP(3);

ALTER TABLE "Post"
  ADD COLUMN IF NOT EXISTS "editedAt" TIMESTAMP(3);

ALTER TABLE "Comment"
  ADD COLUMN IF NOT EXISTS "mentionsJson" TEXT NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "editedAt" TIMESTAMP(3);
